//! Auto-generated bindings for WASI interfaces.
//!
//! This module contains the output of the [`bindgen!`] macro when run over
//! the `wasi:cli/imports` world.
//!
//! [`bindgen!`]: https://docs.rs/wasmtime/latest/wasmtime/component/macro.bindgen.html
//!
//! # Examples
//!
//! If you have a WIT world which refers to `wasi:cli` interfaces you probably want to
//! use this crate's bindings rather than generate fresh bindings. That can be
//! done using the `with` option to [`bindgen!`]:
//!
//! ```rust
//! use core::future::Future;
//!
//! use wasmtime_wasi::p3::cli::{WasiCliCtx, WasiCliView};
//! use wasmtime_wasi::p3::clocks::{WasiClocksCtx, WasiClocksView};
//! use wasmtime_wasi::p3::random::{WasiRandomCtx, WasiRandomView};
//! use wasmtime_wasi::p3::sockets::{WasiSocketsCtx, WasiSocketsView};
//! use wasmtime::{Result, StoreContextMut, Engine, Config};
//! use wasmtime::component::{for_any, Linker};
//!
//! wasmtime::component::bindgen!({
//!     world: "example:wasi/my-world",
//!     inline: "
//!         package example:wasi;
//!
//!         // An example of extending the `wasi:cli/imports` world with a
//!         // custom host interface.
//!         world my-world {
//!             include wasi:cli/imports@0.3.0;
//!
//!             import custom-host;
//!         }
//!
//!         interface custom-host {
//!             my-custom-function: func();
//!         }
//!     ",
//!     path: "src/p3/wit",
//!     with: {
//!         "wasi": wasmtime_wasi::p3::bindings,
//!     },
//!     concurrent_exports: true,
//!     concurrent_imports: true,
//!     async: {
//!         only_imports: [
//!             "example:wasi/custom-host#my-custom-function",
//!             "wasi:clocks/monotonic-clock@0.3.0#wait-for",
//!             "wasi:clocks/monotonic-clock@0.3.0#wait-until",
//!         ],
//!     },
//! });
//!
//! struct MyState {
//!     cli: WasiCliCtx,
//!     clocks: WasiClocksCtx,
//!     random: WasiRandomCtx,
//!     sockets: WasiSocketsCtx,
//!     table: ResourceTable,
//! }
//!
//! impl example::wasi::custom_host::Host for MyState {
//!     type Data = Self;
//!
//!     fn my_custom_function(
//!        store: StoreContextMut<'_, Self::Data>,
//!     ) -> impl Future<
//!         Output = impl FnOnce(StoreContextMut<'_, Self::Data>) + 'static
//!     > + 'static {
//!         async move {
//!             // ..
//!             for_any(|_| {})
//!         }
//!     }
//! }
//!
//! impl WasiCliView for MyState {
//!     fn cli(&self) -> &WasiCliCtx { &self.cli }
//! }
//!
//! impl WasiClocksView for Ctx {
//!     fn clocks(&self) -> &WasiClocksCtx { &self.clocks }
//! }
//!
//! impl WasiRandomView for Ctx {
//!     fn random(&mut self) -> &mut WasiRandomCtx { &mut self.random }
//! }
//!
//! impl WasiSocketsView for Ctx {
//!     fn sockets(&self) -> &WasiSocketsCtx { &self.sockets }
//!
//!     fn table(&mut self) -> &mut ResourceTable { &mut self.table }
//! }
//!
//! fn main() -> Result<()> {
//!     let mut config = Config::default();
//!     config.async_support(true);
//!     let engine = Engine::new(&config)?;
//!     let mut linker: Linker<MyState> = Linker::new(&engine);
//!     wasmtime_wasi::p3::add_to_linker(&mut linker)?;
//!     //example::wasi::custom_host::add_to_linker(&mut linker, |state| state)?;
//!
//!     // .. use `Linker` to instantiate component ...
//!
//!     Ok(())
//! }
//! ```

mod generated {
    wasmtime::component::bindgen!({
        path: "src/p3/wit",
        world: "wasi:cli/command",
        //tracing: true,
        trappable_imports: true,
        concurrent_exports: true,
        concurrent_imports: true,
        async: {
            only_imports: [
                "wasi:clocks/monotonic-clock@0.3.0#wait-for",
                "wasi:clocks/monotonic-clock@0.3.0#wait-until",
                "wasi:sockets/ip-name-lookup@0.3.0#resolve-addresses",
                "wasi:sockets/types@0.3.0#[method]tcp-socket.bind",
                "wasi:sockets/types@0.3.0#[method]tcp-socket.connect",
                "wasi:sockets/types@0.3.0#[method]tcp-socket.listen",
                "wasi:sockets/types@0.3.0#[method]tcp-socket.send",
            ],
        },
        with: {
            "wasi:sockets/types/tcp-socket": crate::p3::sockets::tcp::TcpSocket,
        }
    });
}
pub use self::generated::exports;
pub use self::generated::wasi::*;
pub use self::generated::LinkOptions;

/// Bindings to execute and run a `wasi:cli/command`.
///
/// This structure is automatically generated by `bindgen!`.
///
/// This can be used for a more "typed" view of executing a command component
/// through the [`Command::wasi_cli_run`] method plus
/// [`Guest::call_run`](exports::wasi::cli::run::Guest::call_run).
///
/// # Examples
///
/// ```no_run
/// use wasmtime::{Engine, Result, Store, Config};
/// use wasmtime::component::{ResourceTable, Linker, Component};
/// use wasmtime_wasi::{IoView, WasiCtx, WasiView, WasiCtxBuilder};
/// use wasmtime_wasi::bindings::Command;
///
/// // This example is an example shim of executing a component based on the
/// // command line arguments provided to this program.
/// #[tokio::main]
/// async fn main() -> Result<()> {
///     let args = std::env::args().skip(1).collect::<Vec<_>>();
///
///     // Configure and create `Engine`
///     let mut config = Config::new();
///     config.async_support(true);
///     let engine = Engine::new(&config)?;
///
///     // Configure a `Linker` with WASI, compile a component based on
///     // command line arguments, and then pre-instantiate it.
///     let mut linker = Linker::<MyState>::new(&engine);
///     wasmtime_wasi::add_to_linker_async(&mut linker)?;
///     let component = Component::from_file(&engine, &args[0])?;
///
///
///     // Configure a `WasiCtx` based on this program's environment. Then
///     // build a `Store` to instantiate into.
///     let mut builder = WasiCtxBuilder::new();
///     builder.inherit_stdio().inherit_env().args(&args);
///     let mut store = Store::new(
///         &engine,
///         MyState {
///             ctx: builder.build(),
///             table: ResourceTable::new(),
///         },
///     );
///
///     // Instantiate the component and we're off to the races.
///     let command = Command::instantiate_async(&mut store, &component, &linker).await?;
///     let program_result = command.wasi_cli_run().call_run(&mut store).await?;
///     match program_result {
///         Ok(()) => Ok(()),
///         Err(()) => std::process::exit(1),
///     }
/// }
///
/// struct MyState {
///     ctx: WasiCtx,
///     table: ResourceTable,
/// }
///
/// impl IoView for MyState {
///     fn table(&mut self) -> &mut ResourceTable { &mut self.table }
/// }
/// impl WasiView for MyState {
///     fn ctx(&mut self) -> &mut WasiCtx { &mut self.ctx }
/// }
/// ```
///
/// ---
pub use self::generated::Command;

/// Pre-instantiated analog of [`Command`]
///
/// This can be used to front-load work such as export lookup before
/// instantiation.
///
/// # Examples
///
/// ```no_run
/// use wasmtime::{Engine, Result, Store, Config};
/// use wasmtime::component::{ResourceTable, Linker, Component};
/// use wasmtime_wasi::{IoView, WasiCtx, WasiView, WasiCtxBuilder};
/// use wasmtime_wasi::bindings::CommandPre;
///
/// // This example is an example shim of executing a component based on the
/// // command line arguments provided to this program.
/// #[tokio::main]
/// async fn main() -> Result<()> {
///     let args = std::env::args().skip(1).collect::<Vec<_>>();
///
///     // Configure and create `Engine`
///     let mut config = Config::new();
///     config.async_support(true);
///     let engine = Engine::new(&config)?;
///
///     // Configure a `Linker` with WASI, compile a component based on
///     // command line arguments, and then pre-instantiate it.
///     let mut linker = Linker::<MyState>::new(&engine);
///     wasmtime_wasi::add_to_linker_async(&mut linker)?;
///     let component = Component::from_file(&engine, &args[0])?;
///     let pre = CommandPre::new(linker.instantiate_pre(&component)?)?;
///
///
///     // Configure a `WasiCtx` based on this program's environment. Then
///     // build a `Store` to instantiate into.
///     let mut builder = WasiCtxBuilder::new();
///     builder.inherit_stdio().inherit_env().args(&args);
///     let mut store = Store::new(
///         &engine,
///         MyState {
///             ctx: builder.build(),
///             table: ResourceTable::new(),
///         },
///     );
///
///     // Instantiate the component and we're off to the races.
///     let command = pre.instantiate_async(&mut store).await?;
///     let program_result = command.wasi_cli_run().call_run(&mut store).await?;
///     match program_result {
///         Ok(()) => Ok(()),
///         Err(()) => std::process::exit(1),
///     }
/// }
///
/// struct MyState {
///     ctx: WasiCtx,
///     table: ResourceTable,
/// }
///
/// impl IoView for MyState {
///     fn table(&mut self) -> &mut ResourceTable { &mut self.table }
/// }
/// impl WasiView for MyState {
///     fn ctx(&mut self) -> &mut WasiCtx { &mut self.ctx }
/// }
/// ```
///
/// ---
pub use self::generated::CommandPre;

pub use self::generated::CommandIndices;
